[build]
  # Just build—Next.js will output static files into "out/"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Global security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options        = "DENY"
    X-XSS-Protection       = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy        = "strict-origin-when-cross-origin"

# Caching for static assets
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Netlify Forms
[form]
  name         = "contact"
  action       = "/thank-you"
  method       = "POST"
  data-netlify = "true"

# Disable the Next.js plugin so it doesn't try to publish from your repo root
[[plugins]]
  package = "@netlify/plugin-nextjs"
  enabled = false
