# netlify.toml

[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_SKIP_NEXT_PLUGIN = "true"


# If you need hash-based navigation in SPAs
[[redirects]]
  from = "/#*"
  to   = "/index.html"
  status = 200

# Global security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options         = "DENY"
    X-XSS-Protection        = "1; mode=block"
    X-Content-Type-Options  = "nosniff"
    Referrer-Policy         = "strict-origin-when-cross-origin"

# Cache static assets heavily
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Netlify Forms (if you use them)
[[forms]]
  name = "contact"
