backend:
  name: git-gateway
  branch: main

media_folder: "/"
public_folder: "/"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string", default: "Experience The New Reality"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Button Text", name: "button_text", widget: "string", default: "Explore Us"}
              - {label: "Background Image", name: "background_image", widget: "image", default: "hero-bg.jpg"}
          
          - label: "Mission Section"
            name: "mission"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string", default: "Our Mission"}
              - label: "Mission Items"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
                  - {label: "Icon", name: "icon", widget: "image"}
          
          - label: "Merch Section"
            name: "merch"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string", default: "Merch"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Store URL", name: "store_url", widget: "string", default: "https://redbubble.com/your-store"}
              - {label: "Button Text", name: "button_text", widget: "string", default: "Shop Merch"}
          
          - label: "Contact Section"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string", default: "Contact Us"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Address", name: "address", widget: "text"}
              - {label: "Email", name: "email", widget: "string"}
              - label: "Social Media"
                name: "social"
                widget: "object"
                fields:
                  - {label: "Discord", name: "discord", widget: "string", required: false}
                  - {label: "Twitter", name: "twitter", widget: "string", required: false}
                  - {label: "Pinterest", name: "pinterest", widget: "string", required: false}
                  - {label: "Instagram", name: "instagram", widget: "string", required: false}
                  - {label: "Facebook", name: "facebook", widget: "string", required: false}
                  - {label: "TikTok", name: "tiktok", widget: "string", required: false}
                  - {label: "YouTube", name: "youtube", widget: "string", required: false}

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "site-settings.json"
        fields:
          - {label: "Site Title", name: "title", widget: "string", default: "Screaming Goat Collectibles"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Logo", name: "logo", widget: "image", default: "logo.svg"}
          - {label: "Favicon", name: "favicon", widget: "image", required: false}

  - name: "gallery"
    label: "Gallery"
    folder: "/"
    create: true
    slug: "gallery-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Category", name: "category", widget: "select", options: ["collectibles", "events", "merchandise", "other"]}

  - name: "merch"
    label: "Merchandise"
    folder: "/"
    create: true
    slug: "merch-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Price", name: "price", widget: "string", required: false}
      - {label: "Store Link", name: "store_link", widget: "string", required: false}
